// sources.js - XSEN Feed & Query Configuration

// ─── RSS Feeds ─────────────────────────────────────────────────────────────────
export const RSS_FEEDS = [
  // CONFIRMED WORKING
  { name: 'On3 College Sports',       url: 'https://www.on3.com/feed/',                                        active: true  },
  { name: 'ESPN College Football',    url: 'https://www.espn.com/espn/rss/ncf/news',                          active: true  },
  { name: 'CBS Sports CFB',           url: 'https://www.cbssports.com/rss/headlines/college-football/',        active: true  },
  { name: 'Yahoo CFB',                url: 'https://sports.yahoo.com/college-football/rss.xml',                active: true  },
  { name: 'Front Office Sports',      url: 'https://frontofficesports.com/feed/',                              active: true  },
  { name: 'Sportico',                 url: 'https://www.sportico.com/feed/',                                   active: true  },
  // NEW - test on first Railway run
  { name: 'The Athletic CFB',         url: 'https://theathletic.com/rss/feed',                                 active: true  },
  { name: 'SB Nation CFB',            url: 'https://www.sbnation.com/college-football/rss/current',           active: true  },
  { name: 'Sports Business Journal',  url: 'https://www.sportsbusinessjournal.com/rss/News.aspx',             active: true  },
  { name: 'Awful Announcing',         url: 'https://awfulannouncing.com/feed',                                 active: true  },
  { name: '247Sports CFB',            url: 'https://247sports.com/college/rss/football/',                      active: true  },
  { name: 'Rivals CFB',               url: 'https://n.rivals.com/news.rss',                                    active: true  },
  { name: 'USA Today CFB',            url: 'https://www.usatoday.com/sports/ncaaf/rss/',                      active: true  },
  { name: 'Bleacher Report CFB',      url: 'https://bleacherreport.com/college-football.rss',                 active: true  },
  { name: 'College Football News',    url: 'https://collegefootballnews.com/feed/',                            active: true  },
  { name: 'Saturday Down South',      url: 'https://www.saturdaydownsouth.com/feed/',                         active: true  },
  // CONFIRMED DEAD
  { name: 'NCAA.com FBS',             url: 'https://www.ncaa.com/news/football/fbs/rss',                      active: false },
  { name: 'Fox Sports CFB',           url: 'https://api.foxsports.com/v1/rss?uri=college-football',           active: false },
  { name: 'FanSided CFB',             url: 'https://fansided.com/college-football/feed/',                     active: false },
  { name: 'The Big Lead CFB',         url: 'https://thebiglead.com/feed/',                                    active: false },
  { name: 'Yardbarker CFB',           url: 'https://www.yardbarker.com/rss/college_football',                 active: false },
  { name: 'Heartland College Sports', url: 'https://heartlandcollegesports.com/feed/',                        active: false },
];

// ─── National Google News Queries ─────────────────────────────────────────────
export const NATIONAL_QUERIES = [
  // PE & Money
  'Smash Capital college football',
  'college football private equity investment',
  'college football PE firm deal',
  'Sportico college football money',
  'Sports Business Journal college football',
  'college football media rights deal',
  'college football revenue sharing athletes',
  // NIL
  'NIL collective college football',
  'CFB transfer portal NIL deal',
  'NIL collective shutdown investigation',
  'college football NIL booster investigation',
  'House v NCAA settlement college football',
  'NCAA lawsuit athlete compensation',
  // Realignment
  'Big 12 SEC conference realignment',
  'college football realignment expansion',
  'college football super league PE',
  'college football fan ownership collective',
  // Policy
  'Trump college sports NIL executive order',
  'college sports commission NIL ruling',
  'Front Office Sports college football NIL',
  'NCAA Refuses Settlement college football',
  'college football realignment deals secret',
  // Broadcast
  'college football broadcast rights deal',
  'college football streaming rights ESPN',
  'Awful Announcing college football media',
];

// ─── School Queries (fallback if Supabase unavailable) ────────────────────────
export const SCHOOL_QUERIES = [
  { query: 'Oklahoma Sooners NIL transfer portal',  school: 'OU',    active: true  },
  { query: 'Oklahoma Sooners football',             school: 'OU',    active: true  },
  { query: 'Oklahoma Sooners SEC recruiting',       school: 'OU',    active: true  },
  { query: 'OU Sooners football news',              school: 'OU',    active: true  },
  { query: 'Oklahoma State Cowboys NIL',            school: 'OSU',   active: true  },
  { query: 'Oklahoma State Cowboys football',       school: 'OSU',   active: true  },
  { query: 'OSU Cowboys Big 12 recruiting',         school: 'OSU',   active: true  },
  { query: 'Texas Longhorns NIL collective',        school: 'TEXAS', active: true  },
  { query: 'Texas Longhorns football',              school: 'TEXAS', active: true  },
  { query: 'Texas Longhorns SEC recruiting',        school: 'TEXAS', active: true  },
  { query: 'Alabama Crimson Tide NIL football',     school: 'ALABAMA',    active: false },
  { query: 'Ohio State Buckeyes NIL football',      school: 'OHIO_STATE', active: false },
  { query: 'Georgia Bulldogs NIL football',         school: 'GEORGIA',    active: false },
  { query: 'Michigan Wolverines NIL football',      school: 'MICHIGAN',   active: false },
  { query: 'USC Trojans NIL football',              school: 'USC',        active: false },
  { query: 'Oregon Ducks NIL football',             school: 'OREGON',     active: false },
  { query: 'Penn State Nittany Lions NIL',          school: 'PENN_STATE', active: false },
  { query: 'LSU Tigers NIL football',               school: 'LSU',        active: false },
  { query: 'Clemson Tigers NIL football',           school: 'CLEMSON',    active: false },
  { query: 'Florida State Seminoles NIL',           school: 'FSU',        active: false },
];

// ─── School Config ────────────────────────────────────────────────────────────
export const SCHOOL_CONFIG = {
  OU:         { name: 'Oklahoma Sooners',           fanbase: 'Sooner Nation',       conference: 'SEC',     rivalries: ['Texas', 'Oklahoma State'],  active: true  },
  OSU:        { name: 'Oklahoma State Cowboys',     fanbase: 'Cowboy fans',         conference: 'Big 12',  rivalries: ['Oklahoma'],                 active: true  },
  TEXAS:      { name: 'Texas Longhorns',            fanbase: 'Longhorn Nation',     conference: 'SEC',     rivalries: ['Oklahoma', 'Texas A&M'],    active: true  },
  BAYLOR:     { name: 'Baylor Bears',               fanbase: 'Baylor Nation',       conference: 'Big 12',  rivalries: ['TCU'],                      active: false },
  BYU:        { name: 'BYU Cougars',                fanbase: 'Cougar fans',         conference: 'Big 12',  rivalries: ['Utah'],                     active: false },
  CINCY:      { name: 'Cincinnati Bearcats',        fanbase: 'Bearcat fans',        conference: 'Big 12',  rivalries: ['UCF'],                      active: false },
  COLORADO:   { name: 'Colorado Buffaloes',         fanbase: 'Buff Nation',         conference: 'Big 12',  rivalries: ['Utah'],                     active: false },
  HOUSTON:    { name: 'Houston Cougars',            fanbase: 'Cougar fans',         conference: 'Big 12',  rivalries: ['Cincinnati'],               active: false },
  IOWA_STATE: { name: 'Iowa State Cyclones',        fanbase: 'Cyclone fans',        conference: 'Big 12',  rivalries: ['Iowa'],                     active: false },
  KANSAS:     { name: 'Kansas Jayhawks',            fanbase: 'Jayhawk Nation',      conference: 'Big 12',  rivalries: ['Kansas State'],             active: false },
  KSTATE:     { name: 'Kansas State Wildcats',      fanbase: 'Wildcat fans',        conference: 'Big 12',  rivalries: ['Kansas'],                   active: false },
  TCU:        { name: 'TCU Horned Frogs',           fanbase: 'Frog fans',           conference: 'Big 12',  rivalries: ['Baylor'],                   active: false },
  TEXAS_TECH: { name: 'Texas Tech Red Raiders',     fanbase: 'Red Raider fans',     conference: 'Big 12',  rivalries: ['TCU'],                      active: false },
  UCF:        { name: 'UCF Knights',                fanbase: 'Knight Nation',       conference: 'Big 12',  rivalries: ['Cincinnati'],               active: false },
  UTAH:       { name: 'Utah Utes',                  fanbase: 'Ute fans',            conference: 'Big 12',  rivalries: ['BYU'],                      active: false },
  WVU:        { name: 'West Virginia Mountaineers', fanbase: 'Mountaineer fans',    conference: 'Big 12',  rivalries: ['Pittsburgh'],               active: false },
  ARIZONA:    { name: 'Arizona Wildcats',           fanbase: 'Wildcat fans',        conference: 'Big 12',  rivalries: ['Arizona State'],            active: false },
  ASU:        { name: 'Arizona State Sun Devils',   fanbase: 'Sun Devil fans',      conference: 'Big 12',  rivalries: ['Arizona'],                  active: false },
  ALABAMA:    { name: 'Alabama Crimson Tide',       fanbase: 'Crimson Tide Nation', conference: 'SEC',     rivalries: ['Auburn'],                   active: false },
  ARKANSAS:   { name: 'Arkansas Razorbacks',        fanbase: 'Razorback fans',      conference: 'SEC',     rivalries: ['LSU'],                      active: false },
  AUBURN:     { name: 'Auburn Tigers',              fanbase: 'Tiger fans',          conference: 'SEC',     rivalries: ['Alabama'],                  active: false },
  FLORIDA:    { name: 'Florida Gators',             fanbase: 'Gator Nation',        conference: 'SEC',     rivalries: ['Georgia'],                  active: false },
  GEORGIA:    { name: 'Georgia Bulldogs',           fanbase: 'Bulldog Nation',      conference: 'SEC',     rivalries: ['Florida'],                  active: false },
  KENTUCKY:   { name: 'Kentucky Wildcats',          fanbase: 'Big Blue Nation',     conference: 'SEC',     rivalries: ['Tennessee'],                active: false },
  LSU:        { name: 'LSU Tigers',                 fanbase: 'Tiger Nation',        conference: 'SEC',     rivalries: ['Alabama'],                  active: false },
  MISS_STATE: { name: 'Mississippi State Bulldogs', fanbase: 'Bulldog fans',        conference: 'SEC',     rivalries: ['Ole Miss'],                 active: false },
  MIZZOU:     { name: 'Missouri Tigers',            fanbase: 'Tiger fans',          conference: 'SEC',     rivalries: ['Kansas'],                   active: false },
  OLE_MISS:   { name: 'Ole Miss Rebels',            fanbase: 'Rebel fans',          conference: 'SEC',     rivalries: ['Mississippi State'],        active: false },
  SOUTH_CAR:  { name: 'South Carolina Gamecocks',   fanbase: 'Gamecock fans',       conference: 'SEC',     rivalries: ['Clemson'],                  active: false },
  TENNESSEE:  { name: 'Tennessee Volunteers',       fanbase: 'Vol Nation',          conference: 'SEC',     rivalries: ['Alabama'],                  active: false },
  TAMU:       { name: 'Texas A&M Aggies',           fanbase: 'Aggie Nation',        conference: 'SEC',     rivalries: ['Texas'],                    active: false },
  VANDY:      { name: 'Vanderbilt Commodores',      fanbase: 'Commodore fans',      conference: 'SEC',     rivalries: ['Tennessee'],                active: false },
  MICHIGAN:   { name: 'Michigan Wolverines',        fanbase: 'Wolverine Nation',    conference: 'Big Ten', rivalries: ['Ohio State'],               active: false },
  OHIO_STATE: { name: 'Ohio State Buckeyes',        fanbase: 'Buckeye Nation',      conference: 'Big Ten', rivalries: ['Michigan'],                 active: false },
  PENN_STATE: { name: 'Penn State Nittany Lions',   fanbase: 'Penn State fans',     conference: 'Big Ten', rivalries: ['Ohio State'],               active: false },
  MICH_STATE: { name: 'Michigan State Spartans',    fanbase: 'Spartan fans',        conference: 'Big Ten', rivalries: ['Michigan'],                 active: false },
  IOWA:       { name: 'Iowa Hawkeyes',              fanbase: 'Hawkeye fans',        conference: 'Big Ten', rivalries: ['Iowa State'],               active: false },
  WISCONSIN:  { name: 'Wisconsin Badgers',          fanbase: 'Badger fans',         conference: 'Big Ten', rivalries: ['Minnesota'],                active: false },
  MINNESOTA:  { name: 'Minnesota Golden Gophers',   fanbase: 'Gopher fans',         conference: 'Big Ten', rivalries: ['Wisconsin'],                active: false },
  NEBRASKA:   { name: 'Nebraska Cornhuskers',       fanbase: 'Husker Nation',       conference: 'Big Ten', rivalries: ['Iowa'],                     active: false },
  NORTHWEST:  { name: 'Northwestern Wildcats',      fanbase: 'Wildcat fans',        conference: 'Big Ten', rivalries: ['Illinois'],                 active: false },
  ILLINOIS:   { name: 'Illinois Fighting Illini',   fanbase: 'Illini fans',         conference: 'Big Ten', rivalries: ['Northwestern'],             active: false },
  INDIANA:    { name: 'Indiana Hoosiers',           fanbase: 'Hoosier fans',        conference: 'Big Ten', rivalries: ['Purdue'],                   active: false },
  PURDUE:     { name: 'Purdue Boilermakers',        fanbase: 'Boilermaker fans',    conference: 'Big Ten', rivalries: ['Indiana'],                  active: false },
  RUTGERS:    { name: 'Rutgers Scarlet Knights',    fanbase: 'Scarlet Knight fans', conference: 'Big Ten', rivalries: ['Penn State'],               active: false },
  MARYLAND:   { name: 'Maryland Terrapins',         fanbase: 'Terrapin fans',       conference: 'Big Ten', rivalries: ['Penn State'],               active: false },
  UCLA:       { name: 'UCLA Bruins',                fanbase: 'Bruin fans',          conference: 'Big Ten', rivalries: ['USC'],                      active: false },
  USC:        { name: 'USC Trojans',                fanbase: 'Trojan fans',         conference: 'Big Ten', rivalries: ['UCLA'],                     active: false },
  OREGON:     { name: 'Oregon Ducks',               fanbase: 'Duck fans',           conference: 'Big Ten', rivalries: ['Washington'],               active: false },
  WASHINGTON: { name: 'Washington Huskies',         fanbase: 'Husky fans',          conference: 'Big Ten', rivalries: ['Oregon'],                   active: false },
  CLEMSON:    { name: 'Clemson Tigers',             fanbase: 'Tiger fans',          conference: 'ACC',     rivalries: ['South Carolina'],           active: false },
  FSU:        { name: 'Florida State Seminoles',    fanbase: 'Seminole fans',       conference: 'ACC',     rivalries: ['Florida'],                  active: false },
  MIAMI:      { name: 'Miami Hurricanes',           fanbase: 'Cane fans',           conference: 'ACC',     rivalries: ['Florida State'],            active: false },
  UNC:        { name: 'North Carolina Tar Heels',   fanbase: 'Tar Heel fans',       conference: 'ACC',     rivalries: ['NC State'],                 active: false },
  NC_STATE:   { name: 'NC State Wolfpack',          fanbase: 'Wolfpack fans',       conference: 'ACC',     rivalries: ['UNC'],                      active: false },
  VA_TECH:    { name: 'Virginia Tech Hokies',       fanbase: 'Hokie fans',          conference: 'ACC',     rivalries: ['Virginia'],                 active: false },
  VIRGINIA:   { name: 'Virginia Cavaliers',         fanbase: 'Cavalier fans',       conference: 'ACC',     rivalries: ['Virginia Tech'],            active: false },
  GA_TECH:    { name: 'Georgia Tech Yellow Jackets',fanbase: 'Jacket fans',         conference: 'ACC',     rivalries: ['Georgia'],                  active: false },
  LOUISVILLE: { name: 'Louisville Cardinals',       fanbase: 'Cardinal fans',       conference: 'ACC',     rivalries: ['Kentucky'],                 active: false },
  SYRACUSE:   { name: 'Syracuse Orange',            fanbase: 'Orange fans',         conference: 'ACC',     rivalries: ['Pittsburgh'],               active: false },
  PITT:       { name: 'Pittsburgh Panthers',        fanbase: 'Panther fans',        conference: 'ACC',     rivalries: ['Penn State'],               active: false },
  WAKE:       { name: 'Wake Forest Demon Deacons',  fanbase: 'Deacon fans',         conference: 'ACC',     rivalries: ['NC State'],                 active: false },
  BC:         { name: 'Boston College Eagles',      fanbase: 'Eagle fans',          conference: 'ACC',     rivalries: ['Syracuse'],                 active: false },
  DUKE:       { name: 'Duke Blue Devils',           fanbase: 'Blue Devil fans',     conference: 'ACC',     rivalries: ['UNC'],                      active: false },
  STANFORD:   { name: 'Stanford Cardinal',          fanbase: 'Cardinal fans',       conference: 'ACC',     rivalries: ['Cal'],                      active: false },
  CAL:        { name: 'Cal Bears',                  fanbase: 'Bear fans',           conference: 'ACC',     rivalries: ['Stanford'],                 active: false },
  SMU:        { name: 'SMU Mustangs',               fanbase: 'Mustang fans',        conference: 'ACC',     rivalries: ['TCU'],                      active: false },
};
